### ISSUE TITLE
404 in a lot of pages, no back button.

### ISSUE THREAD

**Issue by Elmapul** [TheLinuxStore/Linux-Store-Html#4]
i added this line

  mainWindow.webContents.openDevTools()

after that line:
  mainWindow.loadURL('file://' + __dirname + '/index.html'); // Load splash screen
so i can debug it.

after booting the program, the console throws:
GET https://linux-store.bitballoon.com/images/icons/google+-icon.png.png 404 ()
preload.html:20 GET https://linux-store.bitballoon.com/images/icons/fpscanner-icon.png 404 ()
preload.html:46 GET https://linux-store.bitballoon.com/images/logos/messanger-logo.png 404 ()
preload.html:51 GET https://linux-store.bitballoon.com/images/logos/arch-logo.png 404 ()

if you click on the disk analyzer program, the program try to acess:
https://linux-store.bitballoon.com/games/Disk-Analyzer/Disk-Analyzer.html
and got stuck into an 404 message (there is no back button)

**Comment by coreybruce** [comment]
Will fix these issues right away, Thank you.
